name: Production workflow

# When workflow is triggered
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Jobs to carry out
jobs:
  Production:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Clone repository
        uses: actions/checkout@v1

      # Install NodeJS
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Run npm install and build on our code
      - run: yarn
      - run: yarn build

      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          yarn global add netlify-cli
          "$(yarn global bin)/netlify" deploy --dir=dist --prod
        
 

